---
name: 'container'
description: 'Run in container.'
author: 'Lisandro Dalcin'

inputs:
  image:
    description: "image"
    required: false
    default: 'ubuntu:latest'
  entrypoint:
    description: "entrypoint"
    required: false
    default:
  args:
    description: "args"
    required: false
    default:

runs:
  using: 'composite'
  steps:
  - uses: docker://${{ inputs.image }}
    with:
      entrypoint: ${{ inputs.entrypoint }}
      args: ${{ inputs.args }}
