name: docker

permissions:
  contents: read

on:
  push:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - fedora:latest
          - debian:latest
          - ubuntu:latest
        platform:
          - amd64
          - arm64
          - ppc64le

    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Run in Docker
        run: |
          docker run \
            --rm \
            -v $(pwd):/${{ github.workspace }} \
            -w ${{ github.workspace }} \
            --platform linux/${{ matrix.platform }} \
            ${{ matrix.image }} \
            bash -c "uname -a; arch; cat /etc/os-release"
