name: docker

permissions:
  contents: read

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian:latest
          - ubuntu:latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/container
      with:
        image: ${{ matrix.image }}
        entrypoint: /bin/bash
        args: test-container.sh
