name: docker

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - fedora:latest
          - debian:latest
          - ubuntu:latest
        arch:
          - x86_64
          - aarch64
          - ppc64le

    steps:

      - uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Run in Docker
        run: |
          docker run \
          -v $(pwd):/${{ github.workspace }} \
          -w ${{ github.workspace }} \
          --platform linux/${{
          matrix.arch == 'x86_64'  && 'amd64'   ||
          matrix.arch == 'aarch64' && 'arm64'   ||
          matrix.arch == 'ppc64le' && 'ppc64le'
          }} ${{ matrix.image }} \
          bash ./test-container.sh
